en:
  answer:
    negative: "ğŸ‘ No"
    positive: "ğŸ‘ Yes"
    wrong: "Sorry, you should select yes or no."
  creator: "ğŸ‘¨â€ğŸ’» Creator\n\nğŸ‡§ğŸ‡¾ @lexvenim"
  error: "ğŸ’€ Error\n\nSorry, something went wrong. Error log has been sent to my /creator, @lexvenim.\nYou should definetely blame him. I did nothing wrong."
  games:
    help: "ğŸ•¹ï¸ Games\n\nIn order to learn new words, it's best to play games. There are two types of games I can offer: translate words or guess which translation is correct.\nIf you don't want to play, type /cancel or press 'Back'."
    info: "ğŸ•¹ï¸ Games\n\nPlease, select your game:"
    select:
      help: "ğŸ”€ Select right translation\n\nRules are simple: I give you a word and 4 translations, you select the one, which is correct. If it's correct, we continue playing. If not - you lose.\nYou can stop playing by typing /cancel. Or an incorrect answer ğŸ˜€"
      not_enough: "ğŸ”€ Select right translation\n\nYou have not enough words in your vocabulary so we can't play games."
      question: "ğŸ”€ Select right translation\n\n%{stats}Translate to %{lang}: %{word}"
      result:
        error: "ğŸ”€ Select right translation\n\nYou're wrong. Game over.\n\nYour score: ğŸ’%{score}."
        success: "Correct!\nYour score: ğŸ’%{score}.\n\n"
    translate:
      help: "ğŸ” Translate words\n\nRules are simple: I give you a word, you give a translation. If it's correct, we continue playing. If not - you lose.\nYou can stop playing by typing /cancel. Or an incorrect answer ğŸ˜€"
      none: "ğŸ” Translate words\n\nYou have no words in your vocabulary so we can't play games."
      question: "ğŸ” Translate words\n\n%{stats}Translate to %{lang}: %{word}"
      result:
        error: "ğŸ” Translate words\n\nYou're wrong. Game over.\n\nYour score: ğŸ’%{score}."
        success: "Correct!\nYour score: ğŸ’%{score}.\n\n"
  hello: "Hello. My name is Revoca. I can help you learn new languages. But I'm not a chat-bot!\nType /help for commands info."
  help:
    creator: "@lexvenim"
    unknown: "Actually, I don't know, what you're doing."
  languages:
    flags:
      en: "ğŸ‡¬ğŸ‡§"
      es: "ğŸ‡ªğŸ‡¸"
      fr: "ğŸ‡«ğŸ‡·"
      ru: "ğŸ‡·ğŸ‡º"
    names:
      en: "English"
      es: "Spanish"
      fr: "French"
      ru: "Russian"
  main:
    help: "My name is Revoca. I can help you learn new languages.\nIf you don't have a vocabulary you need to create one using /new_vocabulary comand. New vocabulary will automatically become active, but if you want to switch back, use /switch_vocabulary.\nEmpty vocabularies are boring: to add a new word type /add_word.\nIf you don't know a translation, it's best to type /translate_word and then save it to your vocabulary.\nTo train your vocabulary type /game and choose a game you want to play.\nTo list the words from your vocabulary type /list_words.\nTo delete a vocabulary use /delete_vocabulary.\nTo change notification settings type /change_notification_settings and follow instructions.\nAlso you can change my main language, just type /change_language.\nHope you'll enjoy working with me. But let's keep it professional."
    info: "Back to menu..."
  menu:
    back: "â¬…ï¸ Back"
    daytime:
      day: "â˜€ï¸ Day"
      evening: "ğŸŒ† Evening"
      morning: "ğŸŒ… Morning"
      night: "ğŸŒ™ Night"
    games:
      select: "ğŸ”€ Select right translation"
      translate: "ğŸ” Translate words"
    help: "â“ Help"
    hour:
      one: "ğŸ•"
      two: "ğŸ•‘"
      three: "ğŸ•’"
      four: "ğŸ•“"
      five: "ğŸ•”"
      six: "ğŸ••"
      seven: "ğŸ•–"
      eight: "ğŸ•—"
      nine: "ğŸ•˜"
      ten: "ğŸ•™"
      eleven: "ğŸ•š"
      twelve: "ğŸ•›"
    main:
      games: "ğŸ•¹ï¸ Games"
      settings: "ğŸ”§ Settings"
      translate: "ğŸ’» Translator"
      vocabulary: "ğŸ“– Vocabularies"
      word: "ğŸ“‹ Words"
    notify:
      day: "1 Day"
      day_two: "2 Days"
      hour_one: "1 Hour"
      hour_two: "2 Hours"
      hour_four: "4 Hours"
      hour_six: "6 Hours"
      hour_twelve: "12 Hours"
      never: "Never"
      week: "1 Week"
    settings:
      info: "â„¹ï¸ Info"
      language: "ğŸ“œ Language"
      notifications: "â° Notification Frequency"
      sleep: "ğŸ›ï¸ Sleep Hours"
    vocabularies:
      add: "ğŸ“• Add vocabulary"
      list: "ğŸ“ƒ List vocabularies"
      switch: "ğŸ“š Switch vocabulary"
      delete: "ğŸ—‘ï¸ Delete vocabulary"
    words:
      add: "âœï¸ Add word"
      list: "ğŸ“ List words"
  settings:
    help: "ğŸ”§ Settings\n\nHere you can view and change your current notification settings. Select 'Period' if you want to change how often you want your notifications. Select 'Sleep Hours' if you want to change time, when I shouldn't bother you.\nIf you don't want to change settings, type /cancel or press 'Back'."
    info: "ğŸ”§ Settings\n\nChoose what you want to change:"
    language:
      choice: "ğŸ“œ Language\n\nSelect language you want:"
      help: "ğŸ“œ Language\n\nHere you can change my primary language. Now I speak to you in English, but you can switch to other languages as well.\nIf you don't want to do change my language, type /cancel or press 'Back'."
      result:
        error: "Something went wrong. Language settings will remain the same."
        success: "Language has been changed."
    notify:
      help: "â° Notification Frequency\n\nHere you can select how often you want my notifications. 1 day is the smallest, 1 week is the largest period.\nBut, if you have sleep hours at notification time, then your notification will be delievered after sleep hours.\nIf you don't want to change notification time, type /cancel or press 'Back'."
      info: "â° Notification Frequency\n\nHow often do you want my notifications?"
      no_vocabulary: "Sorry, you still don't have a vocabulary. Create one and then you can use notifications."
      none: "â° Notification Frequency\n\nYou successfully disabled notifications."
      result:
        error: "Something went wrong. Notification settings will remain the same."
        success: "Notification settings have been changed."
    sleep:
      end: 
        daytime: "ğŸ›ï¸ Sleep Hours\n\nSelect when your sleep hours end:"
        hour: "ğŸ›ï¸ Sleep Hours\n\nSelect exact hour when your sleep hours end:"
        wrong: "Wrong input. Try again."
      help: "ğŸ›ï¸ Sleep Hours\n\nHere you can change my sleep hours. First select part of day when your sleep hours start, then exact time. Next you should the same with its end.\nIf you don't want to change sleep hours, type /cancel or press 'Back'."
      result:
        error: "Something went wrong. Sleep hours settings will remain the same."
        success: "Sleep hours settings have been changed."
      start: 
        daytime: "ğŸ›ï¸ Sleep Hours\n\nSelect when your sleep hours begin:"
        hour: "ğŸ›ï¸ Sleep Hours\n\nSelect exact hour when your sleep hours begin:"
        wrong: "Wrong input. Try again."
    summary: 
      intro: "ğŸ”§ Settings\n\n"
      language: "Your primary language is %{lang}."
      notify:
        negative: "Notifications are disabled.\n\n" 
        positive: "You have notifications %{tick}.\n\n"
      sleep: "Your sleep hours start at %{hour_start}:00 and end at %{hour_end}:00.\n\n"
  time:
    day: "day"
    days: "days"
    every:
      day: "every %{period} day"
      days: "every %{period} days"
      hour: "every %{period} hour"
      hours_1: "every %{period} hours"
      hours_2: "every %{period} hours"
      week: "every %{period} week"
    hour: "hour"
    hours_1: "hours"
    hours_2: "hours"
    week: "week"
  translate:
    help: "ğŸ’» Translator\n\nIt will translate any word you enter. Probably. Give it a try anyway!"
    save:
      none: "You have no words to save."
      result:
        error: "Something went wrong. Word was not added."
        success: "%{word} has been added to vocabulary."
    translation: "ğŸ’» Translator\n\nTranslation: %{translation}.\nIf you want to save it to vocabulary, type /save."
    word: "ğŸ’» Translator\n\nEnter the word to translate:"
  vocabularies:
    delete:
      help: "ğŸ—‘ï¸ Delete vocabulary\n\nHere you can delete vocabularies (if you have more than one).\nIf you don't want to delete a vocabulary, type /cancel or press 'Back'."
      list: "ğŸ—‘ï¸ Delete vocabulary\n\nSelect vocabulary to delete:"
      none: "ğŸ—‘ï¸ Delete vocabulary\n\nYou don't have vocabularies. Can't delete one."
      one: "ğŸ—‘ï¸ Delete vocabulary\n\nYou have only one vocabulary. Can't delete last vocabulary."
      result:
        error: "Something went wrong. Vocabulary was not deleted."
        success: "Vocabulary was successfully deleted."
    help: "ğŸ“– Vocabulary\n\nHere you can manage your vocabularies. You are free to create, switch to and delete vocabularies.\nIf you don't want to do anything with vocabularies, type /cancel or press 'Back'."
    info: "ğŸ“– Vocabulary\n\nChoose what you want to do:"
    list: 
      main: "You have %{num} vocabularies:\n%{vocs}"
      voc: "%{name}: %{count} words"
    new:
      exist: "ğŸ“• Add vocabulary\n\nYou already have such a vocabulary. Why you want another one?"
      help: "ğŸ“• Add vocabulary\n\nHere you can create new vocabulary. First you select language you want to learn, then the language you already know.\nIf you don't want to create a vocabulary, type /cancel or press 'Back'."
      identical: "ğŸ“• Add vocabulary\n\nYou've selected identical languages. Don't think you'll learn something."
      know: "ğŸ“• Add vocabulary\n\nSelect language you already know:"
      learn: "ğŸ“• Add vocabulary\n\nSelect language you want to learn:"
      result:
        error: "Something went wrong. Vocabulary was not created."
        success: "Vocabulary was successfully created."
      wrong: "ğŸ“• Add vocabulary\n\nPlease, type or select correct language." 
    switch:
      help: "ğŸ“š Switch vocabulary\n\nHere you can switch to another vocabulary (if you have more than one).\nIf you don't want to change your vocabulary, type /cancel or press 'Back'."
      list: "ğŸ“š Switch vocabulary\n\nSelect vocabulary to switch to:"
      none: "ğŸ“š Switch vocabulary\n\nYou don't have any vocabularies. Can't switch to one."
      one: "ğŸ“š Switch vocabulary\n\nYou have only one vocabulary."
      result:
        error: "Something went wrong. Vocabulary was not switched."
        success: "Vocabulary was successfully switched."
  words:
    help: "ğŸ“‹ Words\n\nHere you can manage words in your vocabulary. You are free to add and review words.\nIf you don't want to manage your words, type /cancel or press 'Back'."
    info: "ğŸ“‹ Words\n\nChoose what you want to do:"
    list: "%{num} words in your %{llang}-%{klang} vocabulary:\n%{words}"
    new:
      more: "Do you want to add more translations?"
      result:
        error: "Something went wrong. Word was not added."
        success: "%{word} has been added to vocabulary."
      translation: "âœï¸ Add word\n\nPossible translation: %{possible_translation}.\n\nType a translation:"
      word: "âœï¸ Add word\n\nType a word:"
  todo: "Sorry, it's not implemented yet."
  unknown: "It's not a command. I don't understand you. I can help you with learning new words, but I'm not a chat-bot!"